c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - m2w64-sysroot              # [not unix]
c_stdlib_version:
  - "10.13"                    # [osx and x86_64]
  - "11.0"                     # [osx and arm64]
  - "2.28"                     # [linux]
  - "12"                       # [not unix]

c_compiler:
  - clang
c_compiler_version:
  - 19                         # [unix and not aarch64]
  - 18                         # [not unix or aarch64]
cxx_compiler:
  - clangxx
cxx_compiler_version:
  - 19                         # [unix and not aarch64]
  - 18                         # [not unix or aarch64]
