c_stdlib:                       # [not osx]
  - sysroot                     # [linux]
  - m2w64-sysroot               # [not unix]
c_stdlib_version:               # [not osx]
  - 2.34                        # [linux]
  - 12                          # [not unix]

c_compiler:
  - clang                       # [unix]
  - gcc                         # [not unix]
c_compiler_version:
  - 19                          # [unix]
  - 15                          # [not unix]
cxx_compiler:
  - clangxx                     # [unix]
  - gxx                         # [not unix]
cxx_compiler_version:
  - 19                          # [unix]
  - 15                          # [not unix]
