context:
  version: "9.10.1"

package:
  name: ghc-bootstrap
  version: ${{ version }}

source:
  - if: osx
    then:
      url: https://downloads.haskell.org/~ghc/${{ version }}/ghc-${{ version }}-x86_64-apple-darwin.tar.xz
      sha256: 8cf22188930e10d7ac5270d425e21a3dab606af73a655493639345200c650be9
  - if: linux
    then:
      url: https://downloads.haskell.org/~ghc/${{ version }}/ghc-${{ version }}-x86_64-ubuntu20_04-linux.tar.xz
      sha256: ae3be406fdb73bd2b0c22baada77a8ff2f8cde6220dd591dc24541cfe9d895eb
  - if: not unix
    then:
      url: https://downloads.haskell.org/~ghc/${{ version }}/ghc-${{ version }}-x86_64-unknown-mingw32.tar.gz
      sha256: 2e7d766deaaaef95ddc563aebc5f6cbeb286c51a3c124ab31a89a250f88711f9
      target_directory: bootstrap-ghc

build:
  number: 0
  # We would not need a x-compiled ghc-bootstrap
  skip: aarch64 or arm64

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}

    - if: unix
      then:
        - make
        - patchelf
        - perl
      else:
        - m2-bash
        - m2-coreutils
        - m2-findutils
        - m2-which
  host:
    - gmp
    - libffi
  run:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - gmp
    - libffi
    - if: unix
      then:
        - libiconv
        - ncurses

tests:
  - package_contents:
      files:
        - ${PREFIX}/ghc-bootstrap/bin/ghc-${{ version }}${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/ghc-pkg-${{ version }}${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/ghc-pkg${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/ghc-toolchain-bin-ghc-${{ version }}${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/ghc-toolchain-bin${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/ghc${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/ghci-${{ version }}${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/ghci${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/haddock-ghc-${{ version }}${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/haddock${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/hp2ps-ghc-${{ version }}${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/hp2ps${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/hpc-ghc-${{ version }}${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/hpc${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/hsc2hs-ghc-${{ version }}${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/hsc2hs${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/runghc-${{ version }}${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/runghc${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/runhaskell-${{ version }}${{ "" if unix else ".exe" }}
        - ${PREFIX}/ghc-bootstrap/bin/runhaskell${{ "" if unix else ".exe" }}
        - if: not unix
          then:
            - ${PREFIX}/ghc-bootstrap/bin/ghc-iserv-ghc-${{ version }}
            - ${PREFIX}/ghc-bootstrap/bin/ghc-iserv-prof-ghc-${{ version }}
            - ${PREFIX}/ghc-bootstrap/bin/ghc-iserv-prof
            - ${PREFIX}/ghc-bootstrap/bin/ghc-iserv
            - ${PREFIX}/ghc-bootstrap/bin/unlit-ghc-${{ version }}
            - ${PREFIX}/ghc-bootstrap/bin/unlit
            - ${PREFIX}/ghc-bootstrap/bin/ghcii.sh
            - ${PREFIX}/ghc-bootstrap/bin/ghcii9.10.1.sh

  - script: |
      ${PREFIX}/ghc-bootstrap/bin/ghc${{ "" if unix else ".exe" }} --version

  - script: |
      echo 'main = putStrLn "Hello conda-forge"' > hello.hs
      if [[ "$OSTYPE" == "darwin"* ]]; then
        ${PREFIX}/ghc-bootstrap/bin/ghc${{ "" if unix else ".exe" }} -v -L${CONDA_PREFIX}/lib -optl-Wl,-rpath,${CONDA_PREFIX}/lib hello.hs
      else
        ${PREFIX}/ghc-bootstrap/bin/ghc${{ "" if unix else ".exe" }} -v -L${CONDA_PREFIX}/lib hello.hs
      fi
      ./hello${{ "" if unix else ".exe" }}

about:
  homepage: https://haskell.org/ghc/
  license: BSD-3-Clause
  license_file: license_files/
  summary: Glorious Glasgow Haskell Compilation System
  description: |
    GHC is a state-of-the-art, open source, compiler and interactive environment 
    for the functional language Haskell.
  documentation: https://www.haskell.org/ghc/documentation.html
  repository: https://gitlab.haskell.org/ghc/ghc

extra:
  recipe-maintainers:
    - eggzilla
