context:
  version: "9.10.1"

package:
  name: ghc-bootstrap
  version: ${{ version }}

source:
  - if: osx
    then:
      url: https://downloads.haskell.org/~ghc/${{ version }}/ghc-${{ version }}-x86_64-apple-darwin.tar.xz
      sha256: 8cf22188930e10d7ac5270d425e21a3dab606af73a655493639345200c650be9
  - if: linux
    then:
      url: https://downloads.haskell.org/~ghc/${{ version }}/ghc-${{ version }}-x86_64-ubuntu20_04-linux.tar.xz
      sha256: ae3be406fdb73bd2b0c22baada77a8ff2f8cde6220dd591dc24541cfe9d895eb
  - if: not unix
    then:
      url: https://downloads.haskell.org/~ghc/${{ version }}/ghc-${{ version }}-x86_64-unknown-mingw32.tar.gz
      sha256: 2e7d766deaaaef95ddc563aebc5f6cbeb286c51a3c124ab31a89a250f88711f9
      target_directory: bootstrap-ghc

build:
  number: 0
  # We would not need a x-compiled ghc-bootstrap
  skip: aarch64 or arm64

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}

    - if: unix
      then:
        - make
        - patchelf
        - perl
      else:
        - m2-bash
        - m2-findutils
        - m2-which
  host:
    - gmp
    - libffi
  run:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - gmp
    - libffi
    - if: unix
      then:
        - libiconv
        - ncurses

tests:
  - script: |
      ghc-bootstrap --version
  - script: |
      echo 'main = putStrLn "Hello conda-forge"' > hello.hs
      if [[ "$OSTYPE" == "darwin"* ]]; then
        ghc-bootstrap -v -L${CONDA_PREFIX}/lib -optl-Wl,-rpath,${CONDA_PREFIX}/lib hello.hs
      else
        ghc-bootstrap -v -L${CONDA_PREFIX}/lib hello.hs
      fi
      ./hello

about:
  homepage: https://haskell.org/ghc/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Glorious Glasgow Haskell Compilation System
  description: |
    GHC is a state-of-the-art, open source, compiler and interactive environment 
    for the functional language Haskell.
  documentation: https://www.haskell.org/ghc/documentation.html
  repository: https://gitlab.haskell.org/ghc/ghc

extra:
  recipe-maintainers:
    - eggzilla
